/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/utils/Button.vue')['default']
    CityHall: typeof import('./src/components/main/structures/CityHall.vue')['default']
    copy: typeof import('./src/components/main/structures/Void copy.vue')['default']
    Fortress: typeof import('./src/components/main/structures/Fortress.vue')['default']
    GameBar: typeof import('./src/components/GameBar.vue')['default']
    GameCity: typeof import('./src/components/GameCity.vue')['default']
    GameEnter: typeof import('./src/components/GameEnter.vue')['default']
    GameIsland: typeof import('./src/components/GameIsland.vue')['default']
    GameMain: typeof import('./src/components/GameMain.vue')['default']
    GameMainbutton: typeof import('./src/components/main/GameMainbutton.vue')['default']
    GameMainButton: typeof import('./src/components/main/GameMainButton.vue')['default']
    Hospital: typeof import('./src/components/main/structures/Hospital.vue')['default']
    IconCityHall: typeof import('./src/components/main/icons/IconCityHall.vue')['default']
    IconClose: typeof import('./src/components/main/icons/IconClose.vue')['default']
    IconCrystal: typeof import('./src/components/main/icons/IconCrystal.vue')['default']
    IconEvents: typeof import('./src/components/main/icons/IconEvents.vue')['default']
    IconGold: typeof import('./src/components/main/icons/IconGold.vue')['default']
    IconIsland: typeof import('./src/components/main/icons/IconIsland.vue')['default']
    IconMedal: typeof import('./src/components/main/icons/IconMedal.vue')['default']
    IconMedalo: typeof import('./src/components/main/icons/IconMedalo.vue')['default']
    IconMilitary: typeof import('./src/components/main/icons/IconMilitary.vue')['default']
    IconNavy: typeof import('./src/components/main/icons/IconNavy.vue')['default']
    IconPop: typeof import('./src/components/main/icons/IconPop.vue')['default']
    IconScience: typeof import('./src/components/main/icons/IconScience.vue')['default']
    IconStone: typeof import('./src/components/main/icons/IconStone.vue')['default']
    IconSulfur: typeof import('./src/components/main/icons/IconSulfur.vue')['default']
    IconWall: typeof import('./src/components/main/icons/IconWall.vue')['default']
    IconWine: typeof import('./src/components/main/icons/IconWine.vue')['default']
    IconWood: typeof import('./src/components/main/icons/IconWood.vue')['default']
    IconWorld: typeof import('./src/components/main/icons/IconWorld.vue')['default']
    Military: typeof import('./src/components/main/structures/Military.vue')['default']
    Modal: typeof import('./src/components/utils/Modal.vue')['default']
    ResourcesBar: typeof import('./src/components/utils/ResourcesBar.vue')['default']
    Storage: typeof import('./src/components/main/structures/Storage.vue')['default']
    StructureModal: typeof import('./src/components/utils/StructureModal.vue')['default']
    StructureResult: typeof import('./src/components/utils/StructureResult.vue')['default']
    Void: typeof import('./src/components/main/structures/Void.vue')['default']
  }
}
