import { defineStore } from "pinia";
import type { ConstructionTime, PointTime } from "../types";

export const useControllerStore = defineStore("controller", {
  state: () => ({
    constructions: [
      {
        id: "cityhall_0",
        message: "Upgrade cityhall",
        level: {
          2: 18,
          3: 37,
          4: 56,
          5: 86,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
      {
        id: "market_0",
        message: "Upgrade market",
        level: {
          2: 22,
          3: 38,
          4: 58,
          5: 99,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
      {
        id: "military_0",
        message: "Upgrade military",
        level: {
          2: 18,
          3: 37,
          4: 56,
          5: 86,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
      {
        id: "navy_0",
        message: "Upgrade navy",
        level: {
          2: 18,
          3: 37,
          4: 56,
          5: 86,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
      {
        id: "palace_0",
        message: "Upgrade palace",
        level: {
          2: 18,
          3: 37,
          4: 56,
          5: 86,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
      {
        id: "science_0",
        message: "Upgrade science",
        level: {
          2: 18,
          3: 37,
          4: 56,
          5: 86,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
      {
        id: "storage_0",
        message: "Upgrade storage",
        level: {
          2: 18,
          3: 37,
          4: 56,
          5: 86,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
      {
        id: "tavern_0",
        message: "Upgrade tavern",
        level: {
          2: 18,
          3: 37,
          4: 56,
          5: 86,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
      {
        id: "wall_0",
        message: "Upgrade wall",
        level: {
          2: 18,
          3: 37,
          4: 56,
          5: 86,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
      {
        id: "wood_0",
        message: "Upgrade wall",
        level: {
          2: 18,
          3: 37,
          4: 56,
          5: 86,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
      {
        id: "bonus_0",
        message: "Upgrade wall",
        level: {
          2: 18,
          3: 37,
          4: 56,
          5: 86,
        },
        start: false,
        finish: false,
        activeLevel: 2,
      },
    ] as ConstructionTime[],
    units: [
      {
        id: "soldiers_0",
        message: "Your units are ready!",
        start: false,
        finish: false,
        value: 0,
        values: {
          spearman: 0,
          hoplita: 0,
          mech: 0,
          archer: 0,
          catapult: 0,
          wood: 0,
          sulfur: 0,
          stone: 0,
          crystal: 0,
        },
      },
      {
        id: "navy_0",
        message: "Your units are ready!",
        start: false,
        finish: false,
        value: 0,
        values: {
          boats: 0,
          wood: 0,
          sulfur: 0,
          stone: 0,
          crystal: 0,
        },
      },
      {
        id: "naval_soldiers_0",
        message: "Your naval fleet is ready!",
        start: false,
        finish: false,
        value: 0,
        values: {
          galley: 0,
          trireme: 0,
          warship: 0,
          wood: 0,
          sulfur: 0,
          stone: 0,
          crystal: 0,
        },
      },
    ],
    travel: [
      {
        id: "viking_0",
        message: "War against vikings finished!",
        start: false,
        value: 0,
        finish: false,
      },
      {
        id: "bot_attack_0",
        message: "War against bot finished!",
        start: false,
        value: 0,
        finish: false,
      },
      {
        id: "bot_invasion_0",
        message: "Enemy forces are attacking your city!",
        start: false,
        value: 0,
        finish: false,
      },
      {
        id: "colonize_0",
        message: "Colonize finished!",
        start: false,
        value: 0,
        finish: false,
      },
    ],
    points: [
      {
        id: "the_beginning",
        message: "The score at the beginning was researched!",
        description:
          "The beginning: Evolve the first storage one to two level. 14",
        type: "points_economy",
        start: false,
        value: 28,
        finish: false,
      },
      {
        id: "distance",
        message: "The score at distance was researched!",
        description: "Distance: Releases the first character at a distance. 45",
        type: "points_battlefield",
        start: false,
        value: 45,
        finish: false,
      },
      {
        id: "out_to_sea",
        message: "The score at out to sea was researched!",
        description: "Out to sea: You can build the first warship. 28",
        type: "points_travel",
        start: false,
        value: 28,
        finish: false,
      },
      {
        id: "force",
        message: "The score force was researched!",
        description: "Force: Releases hoplita class. 67",
        type: "points_battlefield",
        start: false,
        value: 67,
        finish: false,
      },
      {
        id: "prop",
        message: "The score prop was researched!",
        description: "Prop: Releases catapult class. 123",
        type: "points_battlefield",
        start: false,
        value: 123,
        finish: false,
      },
      {
        id: "mecanize",
        message: "The score mecanize was researched!",
        description: "Mecanize: Releases Mech class. 123",
        type: "points_battlefield",
        start: false,
        value: 302,
        finish: false,
      },
    ] as PointTime[],
  }),
});
